### ISSUE TITLE
Anonymous classes with interfaces missing space before opening bracket cause parse error with PSR-12 ruleset

### ISSUE THREAD

**Issue by jwittorf** [squizlabs/PHP_CodeSniffer#3790]
**Describe the bug**
In some cases anonymous classes with `extends` and `implements` cause a `ParseError` after "fixing" the file.

It happens if there is no space between the last interface-name and the `{`, see following code samples.

The following happens, see code samples at the end:

1. The `new` keyword gets additional `()` braces
2. The interface-names don't get indented and lined up correctly
3. The opening `{` for the class gets removed
4. The methods get wrong

**Code sample**
```php
<?php

namespace Jwittorf\Psr12Linting\Psr12;

use Jwittorf\Psr12Linting\UseableClass;
use Jwittorf\Psr12Linting\Psr4\MultipleInterfaces;
use Jwittorf\Psr12Linting\Psr4\MultipleInterfacesB;
use Jwittorf\Psr12Linting\Psr4\MultipleInterfacesC;
use Jwittorf\Psr12Linting\Psr4\MultipleInterfacesD;

$instance = new class() extends UseableClass implements MultipleInterfaces,
    MultipleInterfacesB,
    MultipleInterfacesC, MultipleInterfacesD{
    public function __construct()
    {
        echo "Created anonymous class in file '" . __FILE__ . "'.\n";
    }

    public function someFunctionToBeImplemented(): void
    {
        echo "This text was created with the function " . __FUNCTION__ . " in file '" . __FILE__ . "'.\n";
    }
};

$instance2 = new class extends UseableClass implements MultipleInterfaces,
                                                       MultipleInterfacesB,
                                                       MultipleInterfacesC, MultipleInterfacesD{
    public function __construct()
    {
        echo "Created anonymous class in file '" . __FILE__ . "'.\n";
    }

    public function someFunctionToBeImplemented(): void
    {
        echo "This text was created with the function " . __FUNCTION__ . " in file '" . __FILE__ . "'.\n";
    }
};

```

**Custom ruleset**
```xml
<?xml version="1.0"?>
<ruleset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="PHP_CodeSniffer">
    <file>src</file>

    <!-- Don't hide tokenizer exceptions -->
    <rule ref="Internal.Tokenizer.Exception">
        <type>error</type>
    </rule>
    
    <rule ref="PSR12"/>
</ruleset>
```

**To reproduce**
1. Create a file called `test.php` with the code sample above...
2. Run `phpcs test.php ...`
3. See messed up PHP code below

```php
<?php

namespace Jwittorf\Psr12Linting\Psr12;

use Jwittorf\Psr12Linting\UseableClass;
use Jwittorf\Psr12Linting\Psr4\MultipleInterfaces;
use Jwittorf\Psr12Linting\Psr4\MultipleInterfacesB;
use Jwittorf\Psr12Linting\Psr4\MultipleInterfacesC;
use Jwittorf\Psr12Linting\Psr4\MultipleInterfacesD;

$instance = new() class () extends UseableClass implements
MultipleInterfaces,
    MultipleInterfacesB,
    MultipleInterfacesC, MultipleInterfacesD

public function __construct()
{
    echo "Created anonymous class in file '" . __FILE__ . "'.\n";
}

public function someFunctionToBeImplemented(): void
{
    echo "This text was created with the function " . __FUNCTION__ . " in file '" . __FILE__ . "'.\n";
}
};

$instance2 = new() class extends UseableClass implements
MultipleInterfaces,
    MultipleInterfacesB,
    MultipleInterfacesC, MultipleInterfacesD

public function __construct()
{
    echo "Created anonymous class in file '" . __FILE__ . "'.\n";
}

public function someFunctionToBeImplemented(): void
{
    echo "This text was created with the function " . __FUNCTION__ . " in file '" . __FILE__ . "'.\n";
}
};

```

**Expected behavior**
I would expect the correct formatting like the code below with following "steps":

1. Put every interface-name on an own line, indented 4 spaces
2. Move the opening `{` into an own line, no indention
3. DON'T try to add `()` after the `new` keyword

```php
<?php

namespace Jwittorf\Psr12Linting\Psr12;

use Jwittorf\Psr12Linting\UseableClass;
use Jwittorf\Psr12Linting\Psr4\MultipleInterfaces;
use Jwittorf\Psr12Linting\Psr4\MultipleInterfacesB;
use Jwittorf\Psr12Linting\Psr4\MultipleInterfacesC;
use Jwittorf\Psr12Linting\Psr4\MultipleInterfacesD;

$instance = new class() extends UseableClass implements
    MultipleInterfaces,
    MultipleInterfacesB,
    MultipleInterfacesC,
    MultipleInterfacesD
{
    public function __construct()
    {
        echo "Created anonymous class in file '" . __FILE__ . "'.\n";
    }

    public function someFunctionToBeImplemented(): void
    {
        echo "This text was created with the function " . __FUNCTION__ . " in file '" . __FILE__ . "'.\n";
    }
};

$instance2 = new class extends UseableClass implements
    MultipleInterfaces,
    MultipleInterfacesB,
    MultipleInterfacesC,
    MultipleInterfacesD
{
    public function __construct()
    {
        echo "Created anonymous class in file '" . __FILE__ . "'.\n";
    }

    public function someFunctionToBeImplemented(): void
    {
        echo "This text was created with the function " . __FUNCTION__ . " in file '" . __FILE__ . "'.\n";
    }
};

```

**Versions:**
 - OS: MacOS 12.6
 - PHP: 7.4.33
 - PHPCS: 3.7.1
 - Standard: PSR12

**Comment by jrfnl** [comment]
@jwittorf Thank you for reporting this. I've been able to reproduce the issues and am working on a fix.

**Comment by jrfnl** [comment]
Okay, done. PR #3791 should fix this. Testing appreciated.

**Comment by jwittorf** [comment]
Thanks for your quick response and fix @jrfnl! I've tested it in my setup, looks good :)

But the [checks for PHP 8.2](https://github.com/squizlabs/PHP_CodeSniffer/actions/runs/4589789779/jobs/8104929083?pr=3791) still fail?

**Comment by jrfnl** [comment]
> Thanks for your quick response and fix @jrfnl! I've tested it in my setup, looks good :)
> 
> But the [checks for PHP 8.2](https://github.com/squizlabs/PHP_CodeSniffer/actions/runs/4589789779/jobs/8104929083?pr=3791) still fail?


Thanks for testing, Re: the PHP 8.2 test run, that is unrelated to this issue. See #3731

**Comment by fredden** [comment]
> > But the [checks for PHP 8.2](https://github.com/squizlabs/PHP_CodeSniffer/actions/runs/4589789779/jobs/8104929083?pr=3791) still fail?
> 
> Thanks for testing, Re: the PHP 8.2 test run, that is unrelated to this issue. See #3731

This specific failure seems to be what is being fixed in https://github.com/squizlabs/PHP_CodeSniffer/pull/3773, not related to #3731.

**Comment by jrfnl** [comment]
@fredden As I pointed out before, they are related. Also: different discussion, not in this issue.

**Comment by fredden** [comment]
@jrfnl it looks like #3791 only addresses one of the four bullet points raised in this issue. Did you determine that the other three are false-alerts / side effects?

> 1. The `new` keyword gets additional `()` braces
> 1. The interface-names don't get indented and lined up correctly
> 1. The opening `{` for the class gets removed
> 1. The methods get wrong

From what I can tell:

1. This seems unrelated to the fix. Perhaps there's a quirk somewhere that adds these parenthesises when the code is mal-formed / invalid?
1. The test case that you've added in #3791 doesn't cover this. Is it covered elsewhere and a side effect of the invalid code?
1. This is directly fixed by #3791.
1. This is fixed by #3791, if I'm reading "wrong" correctly as "not indented enough", because it seems like a side effect from removing the opening brace by mistake.

**Comment by fredden** [comment]
Sorry @jrfnl, I've now seen the note on the pull request which specifically addresses my query.

**Comment by jrfnl** [comment]
FYI: the fix for this issue is included in today's [PHP_CodeSniffer 3.8.0 release](https://github.com/PHPCSStandards/PHP_CodeSniffer/releases/tag/3.8.0).

As per #3932, development on PHP_CodeSniffer will continue in the [PHPCSStandards/PHP_CodeSniffer](https://github.com/PHPCSStandards/PHP_CodeSniffer) repository. If you want to stay informed, you may want to start "watching" that repo (or watching releases from that repo).
